// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package agent

import (
	"ferryman-agent/config"
	"ferryman-agent/data/db"
	"ferryman-agent/data/repo"
	"ferryman-agent/history"
	"ferryman-agent/message"
	"ferryman-agent/permission"
	"ferryman-agent/session"
	"ferryman-agent/tools/workspace"
)

// Injectors from wire.go:

func wireContainer(cfg *config.Config) (*Container, error) {
	databaseConfig := config.DatabaseConfig(cfg)
	dbClient, err := db.NewDbClient(databaseConfig)
	if err != nil {
		return nil, err
	}
	sessionRepo := repo.NewSessionRepo(dbClient)
	service := session.NewService(sessionRepo)
	messageRepo := repo.NewMessageRepo(dbClient)
	messageService := message.NewService(messageRepo)
	historyRepo := repo.NewHistoryRepo(dbClient)
	historyService := history.NewService(historyRepo)
	string2 := config.WorkingDir(cfg)
	permissionService := permission.NewServiceWithWorkingDir(string2)
	workspaceWorkspace := workspace.NewWorkspace(string2)
	v := workspace.NewContainerToolset(workspaceWorkspace, permissionService, historyService)
	container, err := NewContainer(dbClient, service, messageService, historyService, permissionService, workspaceWorkspace, v, sessionRepo, messageRepo, historyRepo)
	if err != nil {
		return nil, err
	}
	return container, nil
}
